USE PerpuSQL
GO

DROP PROCEDURE ADDSISWA
DROP PROCEDURE DELSISWA
DROP PROCEDURE MODSISWA
DROP PROCEDURE SHOWSISWA
DROP PROCEDURE MASTERSISWA
GO

CREATE PROCEDURE ADDSISWA
    (@NAMA_DEPAN NVARCHAR(50),@NAMA_BELAKANG NVARCHAR(70),@JENIS_KELAMIN NVARCHAR(10))
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    PRINT 'TRANSACTION HAS BEGUN'
    BEGIN TRAN
    BEGIN TRY
        PRINT 'DATA INSERT STARTED'
        INSERT INTO MAHASISWA VALUES(@NAMA_DEPAN,@NAMA_BELAKANG,@JENIS_KELAMIN)
        PRINT 'DATA INSERT FINISHED'
        IF @@TRANCOUNT>0
        BEGIN
            PRINT 'NO ERROR OCCURRED, COMMITING'
            COMMIT TRAN
            PRINT 'DATA COMMITED'
        END
    END TRY
    BEGIN CATCH
        PRINT 'ERROR OCCURRED, ROLLING BACK'
        ROLLBACK TRAN
        PRINT 'DATA RESTORED'
    END CATCH
END
GO
CREATE PROCEDURE DELSISWA
    (@ID_MAHASISWA INT,@NAMA_DEPAN NVARCHAR(50),@NAMA_BELAKANG NVARCHAR(70),@JENIS_KELAMIN NVARCHAR(10))
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    PRINT 'TRANSACTION HAS BEGUN'
    BEGIN TRAN
    BEGIN TRY
        PRINT 'DATA DROP STARTED'
        DELETE FROM MAHASISWA WHERE ID_MAHASISWA=@ID_MAHASISWA AND NAMA_DEPAN=@NAMA_DEPAN AND NAMA_BELAKANG=@NAMA_BELAKANG AND JENIS_KELAMIN=@JENIS_KELAMIN
        PRINT 'DATA DROP FINISHED'
        IF @@TRANCOUNT>0
        BEGIN
            PRINT 'NO ERROR OCCURRED, COMMITING'
            COMMIT TRAN
            PRINT 'DATA COMMITED'
        END
    END TRY
    BEGIN CATCH
        PRINT 'ERROR OCCURRED, ROLLING BACK'
        ROLLBACK TRAN
        PRINT 'DATA RESTORED'
    END CATCH
END
GO

CREATE PROCEDURE MODSISWA
    (@ID_MAHASISWA INT,@NAMA_DEPAN NVARCHAR(50),@NAMA_BELAKANG NVARCHAR(70),@JENIS_KELAMIN NVARCHAR(10))
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    PRINT 'TRANSACTION HAS BEGUN'
    BEGIN TRAN
    BEGIN TRY
        PRINT 'DATA UPDATE STARTED'
        UPDATE MAHASISWA
        SET NAMA_DEPAN=@NAMA_DEPAN,NAMA_BELAKANG=@NAMA_BELAKANG,JENIS_KELAMIN=@JENIS_KELAMIN
        WHERE ID_MAHASISWA=@ID_MAHASISWA
        PRINT 'DATA UPDATE FINISHED'
        IF @@TRANCOUNT>0
        BEGIN
            PRINT 'NO ERROR OCCURRED, COMMITING'
            COMMIT TRAN
            PRINT 'DATA COMMITED'
        END
    END TRY
    BEGIN CATCH
        PRINT 'ERROR OCCURRED, ROLLING BACK'
        ROLLBACK TRAN
        PRINT 'DATA RESTORED'
    END CATCH
END
GO

CREATE PROCEDURE SHOWSISWA
AS
    SELECT * FROM MAHASISWA
GO

CREATE PROCEDURE MASTERSISWA
    (@ID_MAHASISWA INT=NULL,@NAMA_DEPAN NVARCHAR(50)=NULL,@NAMA_BELAKANG NVARCHAR(70)=NULL,@JENIS_KELAMIN NVARCHAR(10)=NULL,@COMMAND VARCHAR(20))
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    IF @COMMAND='SELECT'
    BEGIN
        EXEC SHOWSISWA
    END
    ELSE IF @COMMAND='UPDATE'
    BEGIN
        EXEC MODSISWA @ID_MAHASISWA,@NAMA_DEPAN,@NAMA_BELAKANG,@JENIS_KELAMIN
        EXEC SHOWSISWA
    END
    ELSE IF @COMMAND='ADD'
    BEGIN
        PRINT 'ADD'
        EXEC ADDSISWA @NAMA_DEPAN,@NAMA_BELAKANG,@JENIS_KELAMIN
        EXEC SHOWSISWA
    END
    ELSE IF @COMMAND='DELETE'
    BEGIN
        EXEC DELSISWA @ID_MAHASISWA,@NAMA_DEPAN,@NAMA_BELAKANG,@JENIS_KELAMIN
        EXEC SHOWSISWA
    END
    ELSE
    BEGIN
        PRINT 'Available Command=ADD,DELETE,UPDATE,SELECT'
        PRINT 'ADD needs:@NAMA_DEPAN,@NAMA_BELAKANG,@JENIS_KELAMIN'
        PRINT 'DELETE needs:@ID_MAHASISWA,@NAMA_DEPAN,@NAMA_BELAKANG,@JENIS_KELAMIN'
        PRINT 'UPDATE needs:@ID_MAHASISWA,@NAMA_DEPAN,@NAMA_BELAKANG,@JENIS_KELAMIN'
        PRINT 'SELECT is just SELECT * FROM MAHASISWA'
    END
END
GO