-- USE PerpuSQL
-- GO
-- SELECT * FROM BUKU
-- GO
CREATE PROCEDURE ADDBOOK
    (@JUDUL NVARCHAR(90),@ID_PENULIS INT,@ID_GENRE INT)
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    PRINT 'TRANSACTION HAS BEGUN'
    BEGIN TRAN
    BEGIN TRY
        DBCC CHECKIDENT('ID_BUKU',RESEED,0)
        PRINT 'DATA INSERT STARTED'
        INSERT INTO BUKU VALUES(@JUDUL,@ID_PENULIS,@ID_GENRE)
        PRINT 'DATA INSERT FINISHED'
        IF @@TRANCOUNT>0
        BEGIN
            PRINT 'NO ERROR OCCURRED, COMMITING'
            COMMIT TRAN
            PRINT 'DATA COMMITED'
        END
    END TRY
    BEGIN CATCH
        PRINT 'ERROR OCCURRED, ROLLING BACK'
        ROLLBACK TRAN
        PRINT 'DATA RESTORED'
    END CATCH
END