USE PerpuSQL
GO

DROP PROCEDURE ADDBUKU
DROP PROCEDURE DELBUKU
DROP PROCEDURE MODBUKU
DROP PROCEDURE SHOWBUKU
DROP PROCEDURE MASTERBUKU
GO

CREATE PROCEDURE ADDBUKU
    (@JUDUL NVARCHAR(90),@ID_PENULIS INT,@ID_GENRE INT)
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    PRINT 'TRANSACTION HAS BEGUN'
    BEGIN TRAN
    BEGIN TRY
        PRINT 'DATA INSERT STARTED'
        INSERT INTO BUKU VALUES(@JUDUL,@ID_PENULIS,@ID_GENRE)
        PRINT 'DATA INSERT FINISHED'
        IF @@TRANCOUNT>0
        BEGIN
            PRINT 'NO ERROR OCCURRED, COMMITING'
            COMMIT TRAN
            PRINT 'DATA COMMITED'
        END
    END TRY
    BEGIN CATCH
        PRINT 'ERROR OCCURRED, ROLLING BACK'
        ROLLBACK TRAN
        PRINT 'DATA RESTORED'
    END CATCH
END
GO
CREATE PROCEDURE DELBUKU
    (@ID_BUKU INT,@JUDUL NVARCHAR(90),@ID_PENULIS INT, @ID_GENRE INT)
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    PRINT 'TRANSACTION HAS BEGUN'
    BEGIN TRAN
    BEGIN TRY
        PRINT 'DATA DROP STARTED'
        DELETE FROM BUKU WHERE ID_BUKU=@ID_BUKU AND JUDUL=@JUDUL AND ID_PENULIS=@ID_PENULIS AND ID_GENRE=@ID_GENRE
        PRINT 'DATA DROP FINISHED'
        IF @@TRANCOUNT>0
        BEGIN
            PRINT 'NO ERROR OCCURRED, COMMITING'
            COMMIT TRAN
            PRINT 'DATA COMMITED'
        END
    END TRY
    BEGIN CATCH
        PRINT 'ERROR OCCURRED, ROLLING BACK'
        ROLLBACK TRAN
        PRINT 'DATA RESTORED'
    END CATCH
END
GO

CREATE PROCEDURE MODBUKU
    (@ID_BUKU INT, @JUDUL NVARCHAR(90),@ID_PENULIS INT, @ID_GENRE INT)
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    PRINT 'TRANSACTION HAS BEGUN'
    BEGIN TRAN
    BEGIN TRY
        PRINT 'DATA UPDATE STARTED'
        UPDATE BUKU
        SET JUDUL=@JUDUL,ID_PENULIS=@ID_PENULIS,ID_GENRE=@ID_GENRE
        WHERE ID_BUKU=@ID_BUKU
        PRINT 'DATA UPDATE FINISHED'
        IF @@TRANCOUNT>0
        BEGIN
            PRINT 'NO ERROR OCCURRED, COMMITING'
            COMMIT TRAN
            PRINT 'DATA COMMITED'
        END
    END TRY
    BEGIN CATCH
        PRINT 'ERROR OCCURRED, ROLLING BACK'
        ROLLBACK TRAN
        PRINT 'DATA RESTORED'
    END CATCH
END
GO

CREATE PROCEDURE SHOWBUKU
AS
    SELECT ID_BUKU,JUDUL,GENRE,NAMA_DEPAN FROM BUKU B 
    LEFT JOIN GENRE G ON B.ID_GENRE=G.ID_GENRE 
    LEFT JOIN PENULIS P ON B.ID_PENULIS=P.ID_PENULIS
    ORDER BY ID_BUKU ASC
GO

CREATE PROCEDURE MASTERBUKU
    (@ID_BUKU INT=NULL, @JUDUL NVARCHAR(90)=NULL,@ID_PENULIS INT=NULL, @ID_GENRE INT=NULL,@COMMAND VARCHAR(20))
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    IF @COMMAND='SELECT'
    BEGIN
        EXEC SHOWBUKU
    END
    ELSE IF @COMMAND='UPDATE'
    BEGIN
        EXEC MODBUKU @ID_BUKU,@JUDUL,@ID_PENULIS,@ID_GENRE
        EXEC SHOWBUKU
    END
    ELSE IF @COMMAND='ADD'
    BEGIN
        PRINT 'ADD'
        EXEC ADDBUKU @JUDUL,@ID_PENULIS,@ID_GENRE
        EXEC SHOWBUKU
    END
    ELSE IF @COMMAND='DELETE'
    BEGIN
        EXEC DELBUKU @ID_BUKU,@JUDUL,@ID_PENULIS,@ID_GENRE
        EXEC SHOWBUKU
    END
    ELSE
    BEGIN
        PRINT 'Available Command=ADD,DELETE,UPDATE,SELECT'
        PRINT 'ADD needs:@JUDUL,@ID_PENULIS,@ID_GENRE'
        PRINT 'DELETE needs:@ID_BUKU,@JUDUL,@ID_PENULIS,@ID_GENRE'
        PRINT 'UPDATE needs:@ID_BUKU,@JUDUL,@ID_PENULIS,@ID_GENRE'
        PRINT 'SELECT is just SELECT * FROM BUKU'
    END
END
GO