USE PerpuSQL
GO

DROP PROCEDURE ADDPINJAM
DROP PROCEDURE DELPINJAM
DROP PROCEDURE MODPINJAM
DROP PROCEDURE SHOWPINJAM
DROP PROCEDURE MASTERPINJAM
GO

CREATE PROCEDURE ADDPINJAM
    (@ID_MAHASISWA INT,@ID_BUKU INT)
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    PRINT 'TRANSACTION HAS BEGUN'
    BEGIN TRAN
    BEGIN TRY
        PRINT 'DATA INSERT STARTED'
        INSERT INTO PINJAM VALUES(@ID_MAHASISWA,@ID_BUKU,GETDATE(),DATEADD(DAY,+8,DATEADD(MILLISECOND,-3,DATEADD(DAY,0, DATEDIFF(DAY,0,getdate())))))
        PRINT 'DATA INSERT FINISHED'
        IF @@TRANCOUNT>0
        BEGIN
            PRINT 'NO ERROR OCCURRED, COMMITING'
            COMMIT TRAN
            PRINT 'DATA COMMITED'
        END
    END TRY
    BEGIN CATCH
        PRINT 'ERROR OCCURRED, ROLLING BACK'
        ROLLBACK TRAN
        PRINT 'DATA RESTORED'
    END CATCH
END
GO
CREATE PROCEDURE DELPINJAM
    (@ID_PINJAM INT,@ID_MAHASISWA INT,@ID_BUKU NVARCHAR(30))
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    PRINT 'TRANSACTION HAS BEGUN'
    BEGIN TRAN
    BEGIN TRY
        PRINT 'DATA DROP STARTED'
        DELETE FROM PINJAM WHERE ID_PINJAM=@ID_PINJAM AND ID_MAHASISWA=@ID_MAHASISWA AND ID_BUKU=@ID_BUKU
        PRINT 'DATA DROP FINISHED'
        IF @@TRANCOUNT>0
        BEGIN
            PRINT 'NO ERROR OCCURRED, COMMITING'
            COMMIT TRAN
            PRINT 'DATA COMMITED'
        END
    END TRY
    BEGIN CATCH
        PRINT 'ERROR OCCURRED, ROLLING BACK'
        ROLLBACK TRAN
        PRINT 'DATA RESTORED'
    END CATCH
END
GO

CREATE PROCEDURE MODPINJAM
    (@ID_PINJAM INT,@ID_MAHASISWA INT,@ID_BUKU NVARCHAR(30))
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    PRINT 'TRANSACTION HAS BEGUN'
    BEGIN TRAN
    BEGIN TRY
        PRINT 'DATA UPDATE STARTED'
        UPDATE PINJAM
        SET ID_MAHASISWA=@ID_MAHASISWA,ID_BUKU=@ID_BUKU
        WHERE ID_PINJAM=@ID_PINJAM
        PRINT 'DATA UPDATE FINISHED'
        IF @@TRANCOUNT>0
        BEGIN
            PRINT 'NO ERROR OCCURRED, COMMITING'
            COMMIT TRAN
            PRINT 'DATA COMMITED'
        END
    END TRY
    BEGIN CATCH
        PRINT 'ERROR OCCURRED, ROLLING BACK'
        ROLLBACK TRAN
        PRINT 'DATA RESTORED'
    END CATCH
END
GO

CREATE PROCEDURE SHOWPINJAM
AS
    SELECT * FROM PINJAM
GO

CREATE PROCEDURE MASTERPINJAM
    (@ID_PINJAM INT=NULL,@ID_MAHASISWA INT=NULL,@ID_BUKU INT=NULL,@COMMAND VARCHAR(20))
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    IF @COMMAND='SELECT'
    BEGIN
        EXEC SHOWPINJAM
    END
    ELSE IF @COMMAND='UPDATE'
    BEGIN
        EXEC MODPINJAM @ID_PINJAM,@ID_MAHASISWA,@ID_BUKU
        EXEC SHOWPINJAM
    END
    ELSE IF @COMMAND='ADD'
    BEGIN
        PRINT 'ADD'
        EXEC ADDPINJAM @ID_MAHASISWA,@ID_BUKU
        EXEC SHOWPINJAM
    END
    ELSE IF @COMMAND='DELETE'
    BEGIN
        EXEC DELPINJAM @ID_PINJAM,@ID_MAHASISWA,@ID_BUKU
        EXEC SHOWPINJAM
    END
    ELSE
    BEGIN
        PRINT 'Available Command=ADD,DELETE,UPDATE,SELECT'
        PRINT 'ADD needs:@ID_MAHASISWA,@ID_BUKU'
        PRINT 'DELETE needs:@ID_PINJAM,@ID_MAHASISWA,@ID_BUKU'
        PRINT 'UPDATE needs:@ID_PINJAM,@ID_MAHASISWA,@ID_BUKU'
        PRINT 'SELECT is just SELECT * FROM PINJAM'
    END
END
GO