USE [PerpuSQL]
GO
DROP TABLE PINJAM
DROP TABLE MAHASISWA
DROP TABLE BUKU 
DROP TABLE GENRE
DROP TABLE PENULIS
GO
CREATE TABLE PENULIS(
	ID_PENULIS INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NAMA_DEPAN NVARCHAR(50) NOT NULL,
	NAMA_BELAKANG NVARCHAR(70) NOT NULL,
);
GO
CREATE TABLE GENRE(
	ID_GENRE INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	GENRE NVARCHAR(30) NOT NULL,
);
GO
CREATE TABLE BUKU(
	ID_BUKU INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	JUDUL NVARCHAR(90) NOT NULL,
	ID_PENULIS INT NOT NULL FOREIGN KEY REFERENCES PENULIS(ID_PENULIS),
	ID_GENRE INT NOT NULL FOREIGN KEY REFERENCES GENRE(ID_GENRE)
);
GO
CREATE TABLE MAHASISWA(
	ID_MAHASISWA INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NAMA_DEPAN NVARCHAR(50) NOT NULL,
	NAMA_BELAKANG NVARCHAR(70) NOT NULL,
	JENIS_KELAMIN NVARCHAR(10)
);
GO
CREATE TABLE PINJAM(
	ID_PINJAM INT IDENTITY(1,1) NOT NULL,
	ID_MAHASISWA INT NOT NULL FOREIGN KEY REFERENCES MAHASISWA(ID_MAHASISWA),
	ID_BUKU INT NOT NULL FOREIGN KEY REFERENCES BUKU(ID_BUKU),
	TANGGAL_PINJAM DATETIME,
	TANGGAL_KEMBALI DATETIME
);
GO